apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-conf
  namespace : app
data:
  default.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
        location /prod/ {
            # 'backend' must match the name of your Service
            proxy_pass http://backend.app.svc.cluster.local:5001;
        }
    }
