apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  database-url: "postgresql://postgres.idxbfhzdnhidlxklqvsb:R%40th3824our@aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres"
