apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  email-username: pranjalrathore9838@gmail.com
  email-password: aefynjyhyuhnvlse