name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - uses: actions/checkout@v4


      ####################################################
      # Get Semantic Version
      ####################################################

      - name: Get Semantic Version
        id: version
        shell: bash
        run: |
          git fetch --tags

          LAST_TAG=$(git tag --list "v*.*.*" --sort=-v:refname | head -n1)

          if [ -z "$LAST_TAG" ]; then
            VERSION="v1.0.0"
          else
            VERSION=$(echo "$LAST_TAG" | awk -F. -v OFS=. '{$NF++; print}')
          fi

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

          echo "Next Version: $VERSION"

      ###################################################
      # Push DockerHub Images
      ###################################################

      - name: Push Images to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${{ steps.version.outputs.version }}
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

          docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ steps.version.outputs.version }}
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      ####################################################
      # Configure AWS Credentials
      ####################################################

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECERET_KEY }}
          aws-region: ap-south-1

      ####################################################
      # Login to ECR
      ####################################################

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      ####################################################
      # Terraform
      ####################################################

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.0"

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -upgrade -input=false

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      ####################################################
      # Get ECR URLs
      ####################################################

      - name: Get ECR Repository URLs
        working-directory: ./terraform
        run: |
          echo "ECR_URL_FRONTEND=$(terraform output -raw frontend_ecr_repo)" >> "$GITHUB_ENV"
          echo "ECR_URL_BACKEND=$(terraform output -raw backend_ecr_repo)" >> "$GITHUB_ENV"

      ####################################################
      # Tag Images
      ####################################################

      - name: Tag Images for ECR
        run: |
          docker tag \
            ${{ secrets.DOCKER_USERNAME }}/frontend:${{ steps.version.outputs.version }} \
            $ECR_URL_FRONTEND:${{ steps.version.outputs.version }}

          docker tag \
            ${{ secrets.DOCKER_USERNAME }}/frontend:${{ steps.version.outputs.version }} \
            $ECR_URL_FRONTEND:latest

          docker tag \
            ${{ secrets.DOCKER_USERNAME }}/backend:${{ steps.version.outputs.version }} \
            $ECR_URL_BACKEND:${{ steps.version.outputs.version }}

          docker tag \
            ${{ secrets.DOCKER_USERNAME }}/backend:${{ steps.version.outputs.version }} \
            $ECR_URL_BACKEND:latest

      ####################################################
      # Push to ECR
      ####################################################

      - name: Push Images to Amazon ECR
        run: |
          docker push $ECR_URL_FRONTEND:${{ steps.version.outputs.version }}
          docker push $ECR_URL_FRONTEND:latest

          docker push $ECR_URL_BACKEND:${{ steps.version.outputs.version }}
          docker push $ECR_URL_BACKEND:latest

      ####################################################
      # Deploy Frontend
      ####################################################

      - name: Deploy Frontend
        working-directory: ./k8s
        run: |
          helm upgrade --install frontend ./frontend \
            --namespace app \
            --create-namespace \
            --set image.tag=${{ steps.version.outputs.version }}

      ####################################################
      # Deploy Backend
      ####################################################

      - name: Deploy Backend
        working-directory: ./k8s
        run: |
          helm upgrade --install backend ./backend \
            --namespace app \
            --set image.tag=${{ steps.version.outputs.version }}

      ####################################################
      # Verify
      ####################################################

      - name: Verify Frontend
        run: kubectl rollout status deployment/frontend -n app

      - name: Verify Backend
        run: kubectl rollout status deployment/backend -n app

  success-message:
    needs: deploy
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Success
        run: |
          echo "======================================="
          echo "Deployment Successful"
          echo "======================================="