name: CI

on:
  push:
    branches:
      - testing
    tags:
      - "v*.*.*"

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      ####################################################
      # Checkout
      ####################################################

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      ####################################################
      # Get Semantic Version
      ####################################################

      - name: Get Semantic Version
        id: version
        shell: bash
        run: |
          git fetch --tags

          LAST_TAG=$(git tag --list "v*.*.*" --sort=-v:refname | head -n1)

          if [ -z "$LAST_TAG" ]; then
            VERSION="v1.0.0"
          else
            VERSION=$(echo "$LAST_TAG" | awk -F. -v OFS=. '{$NF++; print}')
          fi

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

          echo "Next Version: $VERSION"

      ####################################################
      # Docker Login
      ####################################################

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin

      ####################################################
      # Build Frontend
      ####################################################

      - name: Build Frontend Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/frontend:${{ steps.version.outputs.version }} \
            -t ${{ secrets.DOCKER_USERNAME }}/frontend:test \
            -f ./My-Mart/dockerfile ./My-Mart

      ####################################################
      # Build Backend
      ####################################################

      - name: Build Backend Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/backend:${{ steps.version.outputs.version }} \
            -t ${{ secrets.DOCKER_USERNAME }}/backend:test \
            -f ./martdb/dockerfile ./martdb

      ####################################################
      # Create Kind Cluster
      ####################################################

      - name: Create Kind Cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: kind

     ####################################################
      # Loading Local Image
      ####################################################

      - name: Load Frontend Image
        run: |
          kind load docker-image ${{ secrets.DOCKER_USERNAME }}/frontend:test

      - name: Load Backend Image
        run: |
          kind load docker-image ${{ secrets.DOCKER_USERNAME }}/backend:test

      ####################################################
      # Testing Image - Deploy Frontend 
      ####################################################

      - name: Deploy Frontend
        working-directory: ./k8s
        run: |
          helm upgrade --install frontend ./frontend \
            --namespace testing \
            --create-namespace \
            --set image.tag=test

      ####################################################
      # Testing Image - Deploy Backend
      ####################################################

      - name: Deploy Backend
        working-directory: ./k8s
        run: |
          helm upgrade --install backend ./backend \
            --namespace testing \
            --set image.tag=test

      ####################################################
      # Verify
      ####################################################

      - name: Verify Frontend
        run: kubectl rollout status deployment/frontend -n testing

      - name: Verify Backend
        run: kubectl rollout status deployment/backend -n testing
    
      ####################################################
      # Health Check
      ####################################################

      - name: Health Check
        run: |
          kubectl port-forward svc/frontend 8080:80 -n testing &
          sleep 10
          curl --fail http://localhost:8080/prod/getallProd/


      