name: Deploy My Mart

on:
 push:
  branches: ["main"]

permissions:
 pages: write
 id-token: write

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout Code
     uses: actions/checkout@v4
     
   - name: docker login
     run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
   - name: Build My_Mart Docker Images
     run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend -f ./My-Mart/dockerfile ./My-Mart

   - name: Build My_Mart_DB Docker Image
     run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend -f ./martdb/dockerfile ./martdb
  
   - name: Pushing Image to docker hub
     run: |
           docker push ${{ secrets.DOCKER_USERNAME }}/frontend
           docker push ${{ secrets.DOCKER_USERNAME }}/backend

   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v4
     with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECERET_KEY }}
        aws-region: ap-south-1

   - name: ECR login
     uses: aws-actions/amazon-ecr-login@v2
     with: 
        region: ap-south-1
     id: login-ecr

   - name: Setup Terraform
     uses: hashicorp/setup-terraform@v3
     with:
        terraform_version: "1.14.9" 

   - name: Terraform initialization
     run: terraform init -input=false
     working-directory: ./terraform

   - name: Terraform Plan
     run: terraform plan -out=tfplan -input=false
     working-directory: ./terraform

   - name: Terraform apply
     run: terraform apply -auto-approve
     working-directory: ./terraform

   - name: Get Frontend and Backend ECR URL 
     id: terraform
     working-directory: ./terraform
     run: |
        echo "ECR_URL_FRONTEND=$(terraform output -raw frontend_ecr_repo)" >> $GITHUB_ENV
        echo "ECR_URL_BACKEND=$(terraform output -raw backend_ecr_repo)" >> $GITHUB_ENV

   - name: Taggin images
     run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/frontend:latest $ECR_URL_FRONTEND:latest
        docker tag ${{ secrets.DOCKER_USERNAME }}/backend:latest $ECR_URL_BACKEND:latest

   - name: Pushing images to ECR
     run: |
        docker push $ECR_URL_FRONTEND:latest
        docker push $ECR_URL_BACKEND:latest

   - name: Create k8s Kind Cluster
     uses: helm/kind-action@v1.10.0

   - name: Deploying Frontend on K8s
     run: helm upgrade --install frontend ./frontend --namespace app --create-namespace
     working-directory: ./k8s

   - name: Deploying Backend on K8s
     run: helm upgrade --install backend ./backend -n app
     working-directory: ./k8s
    
   - name: Veryfing Frontend container
     run: kubectl rollout status deployment/frontend -n app

   - name: Veryfing backend container
     run: kubectl rollout status deployment/backend -n app

 success-message: 
    needs: [build]
    runs-on: ubuntu-latest
    if: success()
    steps:
    - run: echo "All jobs passed"
    